# Generated by Django 3.2.3 on 2021-10-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='null', upload_to='packages')),
                ('package_details', models.TextField()),
                ('rating', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('price', models.FloatField()),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
