# Generated by Django 3.2.8 on 2021-11-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_packages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
