# Generated by Django 3.2.8 on 2021-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_destination_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.AddField(
            model_name='packages',
            name='breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packages',
            name='dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packages',
            name='lunch',
            field=models.BooleanField(default=False),
        ),
    ]
