# Generated by Django 3.2.8 on 2021-11-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_packages_decription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='decription',
            new_name='description',
        ),
    ]
