# Generated by Django 3.2.8 on 2021-11-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_rename_decription_packages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image',
            field=models.ImageField(default='null', upload_to='packages'),
        ),
    ]
