# Generated by Django 3.2.8 on 2021-11-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20211114_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
