# Generated by Django 3.2.8 on 2021-11-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_highlight_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='destination',
            name='flights_from',
            field=models.TextField(default=''),
        ),
    ]
