# Generated by Django 3.2.8 on 2021-11-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20211115_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('seat_class', models.CharField(max_length=10)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('adult', models.IntegerField()),
                ('child', models.IntegerField()),
                ('round_trip', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('duration', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('members', models.IntegerField()),
            ],
        ),
    ]
