# Generated by Django 3.2.8 on 2021-11-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_flight_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
